### PR TITLE
[fa] update some statuses

### PR DESCRIPTION
**Pull request by shamsnaamir**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
I will wait for the translation of the [remaining keys](https://github.com/shamsnaamir/http-statuses/blob/main/locales/fa/http-statuses.php).

**Comment by andrey-helldar** [comment]
can you translate [other keys](https://github.com/shamsnaamir/http-statuses/blob/main/locales/fa/http-statuses.php)?

**Comment by shamsnaamir** [comment]
Yes, I'll translate them as soon as possible.

**Comment by andrey-helldar** [comment]
Can you translate the remaining keys so that the file is complete?

**Comment by shamsnaamir** [comment]
Hi
There are no official translations for other statuses but I can translate them myself.
thanks

**Comment by andrey-helldar** [comment]
It would be very cool. Thanks!

**Comment by andrey-helldar** [comment]
Left just a little bit: 226, 221, 424, 449 and 506.

Some of the keys also contain words that are not translated (418, 422 and 523). Is that how it should be?

**Comment by shamsnaamir** [comment]
I think that It'll be completed today
Yes because if I use the translated word, the phrase becomes non-sense.

**Comment by shamsnaamir** [comment]
It's finally finished :tada: :tada: :tada:

**Comment by andrey-helldar** [comment]
Thank you!

**Comment by shamsnaamir** [comment]
your welcome

**Pull request merged**
